name: Deploy image to ECR, update Kubernetes deployment

on:
  push:
    branches:
      - development/feature-1
      - release/v1

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Configure AWS credentials using IAM Role
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: us-east-1
        role-to-assume: arn:aws:iam::050286875379:role/github-action
        role-session-name: GitHubActions # or 'GitHub_to_AWS_via_FederatedOIDC' if first one is not working

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build, tag, and push image to Amazon ECR
      run: |
        docker build -t nakama-server .
        docker tag nakama-server:latest 050286875379.dkr.ecr.us-east-1.amazonaws.com/nakama-server:latest
        docker push 050286875379.dkr.ecr.us-east-1.amazonaws.com/nakama-server:latest

        echo "::set-output name=image::050286875379.dkr.ecr.us-east-1.amazonaws.com/nakama-server:latest

    - name: Update Kubernetes deployment
      env:
        EKS_CLUSTER_NAME: eks-cluster-Arvis
        AWS_REGION: us-east-1
        ECR_IMAGE: 050286875379.dkr.ecr.us-east-1.amazonaws.com/nakama-server:latest
      run: |
        aws eks update-kubeconfig --name ${{ env.EKS_CLUSTER_NAME }} --region us-east-1
        kubectl set image deployment/nakama-prod nakama-prod=${{ env.ECR_IMAGE }}
        kubectl rollout restart deployment/nakama-prod -n default
